import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {

  const titles = await prisma.championship.createManyAndReturn({
    data: [
      { name: "WWE Championship", brand: "SMACKDOWN", division: "MAIN_EVENT" },
      { name: "Universal Championship", brand: "RAW", division: "MAIN_EVENT" },
      { name: "NXT Championship", brand: "NXT", division: "MAIN_EVENT" },
      { name: "Intercontinental Championship", brand: "RAW", division: "MID_CARD" },
      { name: "United States Championship", brand: "SMACKDOWN", division: "MID_CARD" },
      { name: "Raw Women's Championship", brand: "RAW", division: "WOMENS" },
      { name: "SmackDown Women's Championship", brand: "SMACKDOWN", division: "WOMENS" },
      { name: "NXT Women's Championship", brand: "NXT", division: "WOMENS" },
      { name: "Raw Tag Team Championship", brand: "RAW", division: "TAG_TEAM" },
      { name: "SmackDown Tag Team Championship", brand: "SMACKDOWN", division: "TAG_TEAM" },
      { name: "NXT Tag Team Championship", brand: "NXT", division: "TAG_TEAM" },
    ]
  });

  const superstars = await prisma.superstar.createManyAndReturn({
    data: [
      { name: "Aiden English", overall: 75, gender: "M" },
      { name: "AJ Styles", overall: 90, gender: "M" },
      { name: "Akam", overall: 83, gender: "M" },
      { name: "Akira Tozawa", overall: 78, gender: "M" },
      { name: "Albert", overall: 82, gender: "M" },
      { name: "Alexa Bliss", overall: 85, gender: "F" },
      { name: "Alexander Wolfe", overall: 78, gender: "M" },
      { name: "Alicia Fox", overall: 74, gender: "F" },
      { name: "Alundra Blayze", overall: 85, gender: "F" },
      { name: "Apollo Crews", overall: 80, gender: "M" },
      { name: "Asuka", overall: 87, gender: "F" },
      { name: "Bam Bam Bigelow", overall: 85, gender: "M" },
      { name: "Baron Corbin", overall: 84, gender: "M" },
      { name: "Bayley", overall: 83, gender: "F" },
      { name: "Becky Lynch", overall: 83, gender: "F" },
      { name: "Big Cass", overall: 84, gender: "M" },
      { name: "Big E", overall: 86, gender: "M" },
      { name: "Big Show", overall: 82, gender: "M" },
      { name: "Billie Kay", overall: 76, gender: "F" },
      { name: "Bo Dallas", overall: 75, gender: "M" },
      { name: "Bobby Roode", overall: 85, gender: "M" },
      { name: "Booker T", overall: 87, gender: "M" },
      { name: "Braun Strowman", overall: 88, gender: "M" },
      { name: "Bray Wyatt", overall: 85, gender: "M" },
      { name: "Bret Hart", overall: 92, gender: "M" },
      { name: "Brie Bella", overall: 78, gender: "F" },
      { name: "British Bulldog", overall: 84, gender: "M" },
      { name: "Brock Lesnar", overall: 93, gender: "M" },
      { name: "Brutus Beefcake", overall: 84, gender: "M" },
      { name: "Buddy Roberts", overall: 80, gender: "M" },
      { name: "Bushwhacker Butch", overall: 75, gender: "M" },
      { name: "Bushwhacker Luke", overall: 75, gender: "M" },
      { name: "Cactus Jack", overall: 88, gender: "M" },
      { name: "Carmella", overall: 79, gender: "F" },
      { name: "Cedric Alexander", overall: 76, gender: "M" },
      { name: "Cesaro", overall: 86, gender: "M" },
      { name: "Chad Gable", overall: 81, gender: "M" },
      { name: "Charlotte Flair", overall: 85, gender: "F" },
      { name: "Chris Jericho", overall: 87, gender: "M" },
      { name: "Christian", overall: 85, gender: "M" },
      { name: "Curt Hawkins", overall: 72, gender: "M" },
      { name: "Curtis Axel", overall: 78, gender: "M" },
      { name: "Dana Brooke", overall: 75, gender: "F" },
      { name: "Daniel Bryan", overall: 91, gender: "M" },
      { name: "Darren Young", overall: 77, gender: "M" },
      { name: "Dash Wilder", overall: 81, gender: "M" },
      { name: "Dean Ambrose", overall: 88, gender: "M" },
      { name: "Diamond Dallas Page", overall: 89, gender: "M" },
      { name: "Dolph Ziggler", overall: 83, gender: "M" },
      { name: "Dusty Rhodes", overall: 90, gender: "M" },
      { name: "Earthquake", overall: 82, gender: "M" },
      { name: "Eddie Guerrero", overall: 91, gender: "M" },
      { name: "Edge", overall: 91, gender: "M" },
      { name: "Ember Moon", overall: 78, gender: "F" },
      { name: "Emma", overall: 75, gender: "F" },
      { name: "Enzo Amore", overall: 74, gender: "M" },
      { name: "Epico Colon", overall: 77, gender: "M" },
      { name: "Eric Young", overall: 81, gender: "M" },
      { name: "Erick Rowan", overall: 76, gender: "M" },
      { name: "Fandango", overall: 79, gender: "M" },
      { name: "Finn Bálor", overall: 88, gender: "M" },
      { name: "Goldberg", overall: 92, gender: "M" },
      { name: "Goldust", overall: 76, gender: "M" },
      { name: "Gran Metalik", overall: 74, gender: "M" },
      { name: "Greg Valentine", overall: 83, gender: "M" },
      { name: "Heath Slater", overall: 81, gender: "M" },
      { name: "Hideo Itami", overall: 81, gender: "M" },
      { name: "Ivory", overall: 82, gender: "F" },
      { name: "Jack Gallagher", overall: 76, gender: "M" },
      { name: "Jacqueline", overall: 83, gender: "F" },
      { name: "Jake Roberts", overall: 87, gender: "M" },
      { name: "Jason Jordan", overall: 80, gender: "M" },
      { name: "JBL", overall: 86, gender: "M" },
      { name: "Jey Uso", overall: 86, gender: "M" },
      { name: "Jim Neidhart", overall: 84, gender: "M" },
      { name: "Jimmy Garvin", overall: 81, gender: "M" },
      { name: "Jimmy Uso", overall: 86, gender: "M" },
      { name: "Jinder Mahal", overall: 88, gender: "M" },
      { name: "John Cena", overall: 93, gender: "M" },
      { name: "Johnny Gargano", overall: 81, gender: "M" },
      { name: "Kalisto", overall: 75, gender: "M" },
      { name: "Kane", overall: 89, gender: "M" },
      { name: "Karl Anderson", overall: 83, gender: "M" },
      { name: "Kassius Ohno", overall: 80, gender: "M" },
      { name: "Kerry Von Erich", overall: 87, gender: "M" },
      { name: "Kevin Nash", overall: 90, gender: "M" },
      { name: "Kevin Owens", overall: 88, gender: "M" },
      { name: "Kevin Von Erich", overall: 86, gender: "M" },
      { name: "Killian Dain", overall: 78, gender: "M" },
      { name: "Kofi Kingston", overall: 85, gender: "M" },
      { name: "Konnor", overall: 76, gender: "M" },
      { name: "Lita", overall: 84, gender: "F" },
      { name: "Luke Gallows", overall: 83, gender: "M" },
      { name: "Luke Harper", overall: 82, gender: "M" },
      { name: "Mark Henry", overall: 82, gender: "M" },
      { name: "Maryse", overall: 73, gender: "F" },
      { name: "Michael Hayes", overall: 84, gender: "M" },
      { name: "Mickie James", overall: 80, gender: "F" },
      { name: "Mojo Rawley", overall: 80, gender: "M" },
      { name: "Mr. Perfect", overall: 86, gender: "M" },
      { name: "Naomi", overall: 85, gender: "F" },
      { name: "Natalya", overall: 83, gender: "F" },
      { name: "Neville", overall: 84, gender: "M" },
      { name: "Nia Jax", overall: 83, gender: "F" },
      { name: "Nick Miller", overall: 77, gender: "M" },
      { name: "Nikki Bella", overall: 85, gender: "F" },
      { name: "Nikki Cross", overall: 78, gender: "F" },
      { name: "No Way Jose", overall: 79, gender: "M" },
      { name: "Noam Dar", overall: 75, gender: "M" },
      { name: "Paige", overall: 82, gender: "F" },
      { name: "Peyton Royce", overall: 77, gender: "F" },
      { name: "Primo Colon", overall: 77, gender: "M" },
      { name: "R-Truth", overall: 76, gender: "M" },
      { name: "Randy Orton", overall: 90, gender: "M" },
      { name: "Randy Savage", overall: 90, gender: "M" },
      { name: "Rezar", overall: 82, gender: "M" },
      { name: "Rhyno", overall: 81, gender: "M" },
      { name: "Ric Flair", overall: 90, gender: "M" },
      { name: "Rich Swann", overall: 78, gender: "M" },
      { name: "Ricky Steamboat", overall: 90, gender: "M" },
      { name: "Rikishi", overall: 83, gender: "M" },
      { name: "Roderick Strong", overall: 80, gender: "M" },
      { name: "Roman Reigns", overall: 95, gender: "M" },
      { name: "Rusev", overall: 84, gender: "M" },
      { name: "Sami Zayn", overall: 84, gender: "M" },
      { name: "Samoa Joe", overall: 88, gender: "M" },
      { name: "Sasha Banks", overall: 84, gender: "F" },
      { name: "Sawyer Fulton", overall: 69, gender: "M" },
      { name: "Scott Dawson", overall: 81, gender: "M" },
      { name: "Scott Hall", overall: 86, gender: "M" },
      { name: "Seth Rollins", overall: 92, gender: "M" },
      { name: "Shane McMahon", overall: 84, gender: "M" },
      { name: "Shane Thorne", overall: 78, gender: "M" },
      { name: "Shawn Michaels", overall: 90, gender: "M" },
      { name: "Sheamus", overall: 85, gender: "M" },
      { name: "Shinsuke Nakamura", overall: 89, gender: "M" },
      { name: "Sin Cara", overall: 75, gender: "M" },
      { name: "Steve Austin", overall: 92, gender: "M" },
      { name: "Sting", overall: 89, gender: "M" },
      { name: "Summer Rae", overall: 73, gender: "F" },
      { name: "Sycho Sid", overall: 88, gender: "M" },
      { name: "Tamina", overall: 76, gender: "F" },
      { name: "The Brian Kendrick", overall: 76, gender: "M" },
      { name: "The Miz", overall: 87, gender: "M" },
      { name: "The Rock", overall: 93, gender: "M" },
      { name: "Titus O'Neil", overall: 77, gender: "M" },
      { name: "TJP", overall: 79, gender: "M" },
      { name: "Tommaso Ciampa", overall: 79, gender: "M" },
      { name: "Triple H", overall: 89, gender: "M" },
      { name: "Trish Stratus", overall: 85, gender: "F" },
      { name: "Tye Dillinger", overall: 80, gender: "M" },
      { name: "Tyler Breeze", overall: 79, gender: "M" },
      { name: "Typhoon", overall: 82, gender: "M" },
      { name: "Tyson Kidd", overall: 76, gender: "M" },
      { name: "Ultimate Warrior", overall: 91, gender: "M" },
      { name: "Undertaker", overall: 89, gender: "M" },
      { name: "Vader", overall: 89, gender: "M" },
      { name: "Viktor", overall: 76, gender: "M" },
      { name: "Xavier Woods", overall: 83, gender: "M" },
      { name: "Zack Ryder", overall: 81, gender: "M" },
    ],
  });

  const teams = await prisma.tagTeam.createManyAndReturn({
    data: [
      { name: "#DIY" },
      { name: "Alexander & Swann" },
      { name: "American Alpha" },
      { name: "Breezango" },
      { name: "DDP & Cactus Jack" },
      { name: "Enzo & Cass" },
      { name: "Gallows & Anderson" },
      { name: "Itami & Tozawa" },
      { name: "Kendrick & Gallagher" },
      { name: "SAnitY" },
      { name: "Slater & Rhyno" },
      { name: "The Ascension" },
      { name: "The Authors of Pain" },
      { name: "The B-Team" },
      { name: "The Bar" },
      { name: "The Bushwhackers" },
      { name: "The Colons" },
      { name: "The Dream Team" },
      { name: "The Fabulous Freebirds" },
      { name: "The Golden Truth" },
      { name: "The Hart Foundation" },
      { name: "The Hype Bros" },
      { name: "The Lucha Dragons" },
      { name: "The Natural Disasters" },
      { name: "The New Day" },
      { name: "The Outsiders" },
      { name: "The Revival" },
      { name: "The Usos" },
      { name: "The Von Erichs" },
      { name: "The Wyatt Family" },
      { name: "Titus Worldwide" },
      { name: "TM-61" },
    ]
  });

  const teamMembers: Record<string, Array<string>> = {
    "#DIY": ["Johnny Gargano", "Tommaso Ciampa"],
    "Alexander & Swann": ["Cedric Alexander", "Rich Swann"],
    "American Alpha": ["Chad Gable", "Jason Jordan"],
    "Breezango": ["Tyler Breeze", "Fandango"],
    "DDP & Cactus Jack": ["Diamond Dallas Page", "Cactus Jack"],
    "Enzo & Cass": ["Enzo Amore", "Big Cass"],
    "Gallows & Anderson": ["Luke Gallows", "Karl Anderson"],
    "Itami & Tozawa": ["Hideo Itami", "Akira Tozawa"],
    "Kendrick & Gallagher": ["The Brian Kendrick", "Jack Gallagher"],
    "SAnitY": ["Eric Young", "Alexander Wolfe", "Killian Dain"],
    "Slater & Rhyno": ["Heath Slater", "Rhyno"],
    "The Ascension": ["Konnor", "Viktor"],
    "The Authors of Pain": ["Akam", "Rezar"],
    "The B-Team": ["Curtis Axel", "Bo Dallas"],
    "The Bar": ["Sheamus", "Cesaro"],
    "The Bushwhackers": ["Bushwhacker Butch", "Bushwhacker Luke"],
    "The Colons": ["Primo Colon", "Epico Colon"],
    "The Dream Team": ["Brutus Beefcake", "Greg Valentine"],
    "The Fabulous Freebirds": ["Michael Hayes", "Buddy Roberts", "Jimmy Garvin"],
    "The Golden Truth": ["Goldust", "R-Truth"],
    "The Hart Foundation": ["Jim Neidhart", "British Bulldog"],
    "The Hype Bros": ["Zack Ryder", "Mojo Rawley"],
    "The Lucha Dragons": ["Kalisto", "Sin Cara"],
    "The Natural Disasters": ["Earthquake", "Typhoon"],
    "The New Day": ["Big E", "Kofi Kingston", "Xavier Woods"],
    "The Outsiders": ["Kevin Nash", "Scott Hall"],
    "The Revival": ["Dash Wilder", "Scott Dawson"],
    "The Usos": ["Jimmy Uso", "Jey Uso"],
    "The Von Erichs": ["Kerry Von Erich", "Kevin Von Erich"],
    "The Wyatt Family": ["Luke Harper", "Erick Rowan"],
    "Titus Worldwide": ["Titus O'Neil", "Apollo Crews"],
    "TM-61": ["Nick Miller", "Shane Thorne"],
  };

  const teamMemberData: Array<{ tagTeamId: number, superstarId: number, order: number }> = [];
  for (const [teamName, members] of Object.entries(teamMembers)) {
    const tagTeamId = getItemByName(teams, teamName).id;
    for (let index = 0; index < members.length; index++) {
      const superstarId = getItemByName(superstars, members[index]).id;
      teamMemberData.push({ tagTeamId, superstarId, order: index });
    }
  }

  await prisma.tagTeamMembership.createMany({
    data: teamMemberData
  });
}

function getItemByName(list: Array<{ name: string, id: number }>, name: string) {
  const item = list.find(i => i.name === name);
  if (!item) throw new Error(`Failed to find item: ${name}`);
  return item;
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });